### PR TITLE
Video not loading, keywords null

### PR DESCRIPTION
**Pull request by YabberWalkie**
Youtube video's not loading because item["keywords"] is None

### CODE REVIEW

**Comment by Shagon94** [comment]
can confirm this fixes the new issue, thanks @Helza

**Comment by piotr555** [comment]
Confirm. Can't use the plugin without this patch.
Thanks @Helza!

**Comment by eaconner** [comment]
Thanks @Helza! This patch fixed the plugin for me also.

**Comment by supwner** [comment]
Confirmed videos are playing again. Thanx.

**Comment by MeanLauraJean** [comment]
This didn't fix the problem for the videos that won't play for me. An example would be https://www.youtube.com/watch?v=KtlgYxa6BMU

Is this a different issue?

**Comment by CollinChaffin** [comment]
@MeanLauraJean Yes it is a different issue.  That video is one that requires yet another sig parsing update on top of this PR.  If I get a min I will put together a PR.

**Comment by YabberWalkie** [comment]
Yeah i updated my repo with the signature fix for this but didnt submit a PR as the first one wasnt approved yet

**Comment by MeanLauraJean** [comment]
Thanks @Helza!

**Pull request merged**
